2023-04-21 11:21:57,420 INFO    MainThread:8047 [wandb_setup.py:_flush():76] Configure stats pid to 8047
2023-04-21 11:21:57,420 INFO    MainThread:8047 [wandb_setup.py:_flush():76] Loading settings from /Users/MaryFetter/.config/wandb/settings
2023-04-21 11:21:57,420 INFO    MainThread:8047 [wandb_setup.py:_flush():76] Loading settings from /Users/MaryFetter/Documents/GitHub/NCANDA_Contrastive/wandb/settings
2023-04-21 11:21:57,420 INFO    MainThread:8047 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-21 11:21:57,420 INFO    MainThread:8047 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-21 11:21:57,420 INFO    MainThread:8047 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2023-04-21 11:21:57,421 INFO    MainThread:8047 [wandb_init.py:_log_setup():507] Logging user logs to /Users/MaryFetter/Documents/GitHub/NCANDA_Contrastive/wandb/run-20230421_112157-4p9bazrs/logs/debug.log
2023-04-21 11:21:57,421 INFO    MainThread:8047 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/MaryFetter/Documents/GitHub/NCANDA_Contrastive/wandb/run-20230421_112157-4p9bazrs/logs/debug-internal.log
2023-04-21 11:21:57,421 INFO    MainThread:8047 [wandb_init.py:init():547] calling init triggers
2023-04-21 11:21:57,421 INFO    MainThread:8047 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2023-04-21 11:21:57,421 INFO    MainThread:8047 [wandb_init.py:init():595] starting backend
2023-04-21 11:21:57,421 INFO    MainThread:8047 [wandb_init.py:init():599] setting up manager
2023-04-21 11:21:57,441 INFO    MainThread:8047 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-04-21 11:21:57,448 INFO    MainThread:8047 [wandb_init.py:init():605] backend started and connected
2023-04-21 11:21:57,462 INFO    MainThread:8047 [wandb_init.py:init():695] updated telemetry
2023-04-21 11:21:57,497 INFO    MainThread:8047 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-21 11:21:57,694 ERROR   MainThread:8047 [wandb_init.py:init():758] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-04-21 11:21:57,776 ERROR   MainThread:8047 [wandb_init.py:init():1163] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-04-21 11:21:58,782 WARNING MsgRouterThr:8047 [router.py:message_loop():77] message_loop has been closed
